use [STAGE_Support];

Update KbArticles set PremiumType = '# Days Required', Status='Published', IsExternal = 'Y' where solNumber = 'SW3779';
Update KbArticles set PremiumType = 'Not Required', Status='Published', IsExternal = 'Y' where solNumber = '143174';
Update KbArticles set PremiumType = '# Days Required', Status='Published', IsExternal = 'Y' where solNumber = '144377';
Update KbArticles set PremiumType = 'Always Required', Status='Published', IsExternal = 'Y' where solNumber = '144709';
Update KbArticles set PremiumType = '# Days Required', Status='Published', IsExternal = 'N' where solNumber = '144690';
Update KbArticles set PremiumType = 'Not Required', Status='QuickShare', IsExternal = 'Y' where solNumber = '144969';
Update KbArticles set PremiumType = '# Days Required', Status='QuickShare', IsExternal = 'Y' where solNumber = '145370';
Update KbArticles set PremiumType = 'Always Required', Status='QuickShare', IsExternal = 'Y' where solNumber = '145471';
Update KbArticles set PremiumType = '# Days Required', Status='QuickShare', IsExternal = 'N' where solNumber = '145567';
Update KbArticles set PremiumType = '# Days Required', Status='Submitted', IsExternal = 'Y' where solNumber = '145664';
Update KbArticles set PremiumType = '# Days Required', Status='Submitted', IsExternal = 'N' where solNumber = '146291';
Update KbArticles set PremiumType = '# Days Required', Status='Published', IsExternal = 'Y' where solNumber = 'SW3779';
Update KbArticles set PremiumType = 'Not Required', Status='Published', IsExternal = 'Y' where solNumber = '205086';
Update KbArticles set PremiumType = '# Days Required', Status='Published', IsExternal = 'Y' where solNumber = '105445';
Update KbArticles set PremiumType = 'Always Required', Status='Published', IsExternal = 'Y' where solNumber = '207089';
Update KbArticles set PremiumType = '# Days Required', Status='Published', IsExternal = 'N' where solNumber = '208127';
Update KbArticles set PremiumType = 'Not Required', Status='QuickShare', IsExternal = 'Y' where solNumber = '122362';
Update KbArticles set PremiumType = '# Days Required', Status='QuickShare', IsExternal = 'Y' where solNumber = '154054';
Update KbArticles set PremiumType = 'Always Required', Status='QuickShare', IsExternal = 'Y' where solNumber = '207847';
Update KbArticles set PremiumType = '# Days Required', Status='QuickShare', IsExternal = 'N' where solNumber = '208183';
Update KbArticles set PremiumType = '# Days Required', Status='Submitted', IsExternal = 'Y' where solNumber = '122182';
Update KbArticles set PremiumType = '# Days Required', Status='Submitted', IsExternal = 'N' where solNumber = '122569';
Update KbArticles set PremiumType = '# Days Required', Status='Published', IsExternal = 'Y' where solNumber = 'SW3779';
Update KbArticles set PremiumType = 'Not Required', Status='Published', IsExternal = 'Y' where solNumber = '121620';
Update KbArticles set PremiumType = '# Days Required', Status='Published', IsExternal = 'Y' where solNumber = '113775';
Update KbArticles set PremiumType = 'Always Required', Status='Published', IsExternal = 'Y' where solNumber = '116532';
Update KbArticles set PremiumType = '# Days Required', Status='Published', IsExternal = 'N' where solNumber = '204961';
Update KbArticles set PremiumType = 'Not Required', Status='QuickShare', IsExternal = 'Y' where solNumber = '116192';
Update KbArticles set PremiumType = '# Days Required', Status='QuickShare', IsExternal = 'Y' where solNumber = '116638';
Update KbArticles set PremiumType = 'Always Required', Status='QuickShare', IsExternal = 'Y' where solNumber = '119393';
Update KbArticles set PremiumType = '# Days Required', Status='QuickShare', IsExternal = 'N' where solNumber = '210056';
Update KbArticles set PremiumType = '# Days Required', Status='Submitted', IsExternal = 'Y' where solNumber = '30557';
Update KbArticles set PremiumType = '# Days Required', Status='Submitted', IsExternal = 'N' where solNumber = '102619';
Update KbArticles set PremiumType = '# Days Required', Status='Published', IsExternal = 'Y' where solNumber = 'SW3779';
Update KbArticles set PremiumType = 'Not Required', Status='Published', IsExternal = 'Y' where solNumber = '143174';
Update KbArticles set PremiumType = '# Days Required', Status='Published', IsExternal = 'Y' where solNumber = '144377';
Update KbArticles set PremiumType = 'Always Required', Status='Published', IsExternal = 'Y' where solNumber = '144709';
Update KbArticles set PremiumType = '# Days Required', Status='Published', IsExternal = 'N' where solNumber = '144690';
Update KbArticles set PremiumType = 'Not Required', Status='QuickShare', IsExternal = 'Y' where solNumber = '144969';
Update KbArticles set PremiumType = '# Days Required', Status='QuickShare', IsExternal = 'Y' where solNumber = '145370';
Update KbArticles set PremiumType = 'Always Required', Status='QuickShare', IsExternal = 'Y' where solNumber = '145471';
Update KbArticles set PremiumType = '# Days Required', Status='QuickShare', IsExternal = 'N' where solNumber = '145567';
Update KbArticles set PremiumType = '# Days Required', Status='Submitted', IsExternal = 'Y' where solNumber = '145664';
Update KbArticles set PremiumType = '# Days Required', Status='Submitted', IsExternal = 'N' where solNumber = '146291';
Update KbArticles set PremiumType = '# Days Required', Status='Published', IsExternal = 'Y' where solNumber = 'SW3779';
Update KbArticles set PremiumType = 'Not Required', Status='Published', IsExternal = 'Y' where solNumber = '143174';
Update KbArticles set PremiumType = '# Days Required', Status='Published', IsExternal = 'Y' where solNumber = '144377';
Update KbArticles set PremiumType = 'Always Required', Status='Published', IsExternal = 'Y' where solNumber = '144709';
Update KbArticles set PremiumType = '# Days Required', Status='Published', IsExternal = 'N' where solNumber = '144690';
Update KbArticles set PremiumType = 'Not Required', Status='QuickShare', IsExternal = 'Y' where solNumber = '144969';
Update KbArticles set PremiumType = '# Days Required', Status='QuickShare', IsExternal = 'Y' where solNumber = '145370';
Update KbArticles set PremiumType = 'Always Required', Status='QuickShare', IsExternal = 'Y' where solNumber = '145471';
Update KbArticles set PremiumType = '# Days Required', Status='QuickShare', IsExternal = 'N' where solNumber = '145567';
Update KbArticles set PremiumType = '# Days Required', Status='Submitted', IsExternal = 'Y' where solNumber = '145664';
Update KbArticles set PremiumType = '# Days Required', Status='Submitted', IsExternal = 'N' where solNumber = '146291';
Update KbArticles set PremiumType = '# Days Required', Status='Published', IsExternal = 'Y' where solNumber = 'SW3779';
Update KbArticles set PremiumType = 'Not Required', Status='Published', IsExternal = 'Y' where solNumber = '125645';
Update KbArticles set PremiumType = '# Days Required', Status='Published', IsExternal = 'Y' where solNumber = '129135';
Update KbArticles set PremiumType = 'Always Required', Status='Published', IsExternal = 'Y' where solNumber = '126739';
Update KbArticles set PremiumType = '# Days Required', Status='Published', IsExternal = 'N' where solNumber = '123045';
Update KbArticles set PremiumType = 'Not Required', Status='QuickShare', IsExternal = 'Y' where solNumber = '144592';
Update KbArticles set PremiumType = '# Days Required', Status='QuickShare', IsExternal = 'Y' where solNumber = '144604';
Update KbArticles set PremiumType = 'Always Required', Status='QuickShare', IsExternal = 'Y' where solNumber = '145132';
Update KbArticles set PremiumType = '# Days Required', Status='QuickShare', IsExternal = 'N' where solNumber = '145374';
Update KbArticles set PremiumType = '# Days Required', Status='Submitted', IsExternal = 'Y' where solNumber = '145393';
Update KbArticles set PremiumType = '# Days Required', Status='Submitted', IsExternal = 'N' where solNumber = '145507';
Update KbArticles set PremiumType = '# Days Required', Status='Published', IsExternal = 'Y' where solNumber = 'SW3779';
Update KbArticles set PremiumType = 'Not Required', Status='Published', IsExternal = 'Y' where solNumber = '122136';
Update KbArticles set PremiumType = '# Days Required', Status='Published', IsExternal = 'Y' where solNumber = '126049';
Update KbArticles set PremiumType = 'Always Required', Status='Published', IsExternal = 'Y' where solNumber = '145398';
Update KbArticles set PremiumType = '# Days Required', Status='Published', IsExternal = 'N' where solNumber = '121368';
Update KbArticles set PremiumType = 'Not Required', Status='QuickShare', IsExternal = 'Y' where solNumber = '148479';
Update KbArticles set PremiumType = '# Days Required', Status='QuickShare', IsExternal = 'Y' where solNumber = '128669';
Update KbArticles set PremiumType = 'Always Required', Status='QuickShare', IsExternal = 'Y' where solNumber = '121666';
Update KbArticles set PremiumType = '# Days Required', Status='QuickShare', IsExternal = 'N' where solNumber = '128832';
Update KbArticles set PremiumType = '# Days Required', Status='Submitted', IsExternal = 'Y' where solNumber = '151393';
Update KbArticles set PremiumType = '# Days Required', Status='Submitted', IsExternal = 'N' where solNumber = '152017';
Update KbArticles set PremiumType = '# Days Required', Status='Published', IsExternal = 'Y' where solNumber = 'SW3779';
Update KbArticles set PremiumType = 'Not Required', Status='Published', IsExternal = 'Y' where solNumber = '143174';
Update KbArticles set PremiumType = '# Days Required', Status='Published', IsExternal = 'Y' where solNumber = '144377';
Update KbArticles set PremiumType = 'Always Required', Status='Published', IsExternal = 'Y' where solNumber = '144709';
Update KbArticles set PremiumType = '# Days Required', Status='Published', IsExternal = 'N' where solNumber = '144690';
Update KbArticles set PremiumType = 'Not Required', Status='QuickShare', IsExternal = 'Y' where solNumber = '144969';
Update KbArticles set PremiumType = '# Days Required', Status='QuickShare', IsExternal = 'Y' where solNumber = '145370';
Update KbArticles set PremiumType = 'Always Required', Status='QuickShare', IsExternal = 'Y' where solNumber = '145471';
Update KbArticles set PremiumType = '# Days Required', Status='QuickShare', IsExternal = 'N' where solNumber = '145567';
Update KbArticles set PremiumType = '# Days Required', Status='Submitted', IsExternal = 'Y' where solNumber = '145664';
Update KbArticles set PremiumType = '# Days Required', Status='Submitted', IsExternal = 'N' where solNumber = '146291';
