*** Variables ***
${dsg_home_ToolsTitle_msr_locator}    xpath=//div[@id="Tools"]//span[@class="tools-title"][text()[contains(., '${dsg_home_ToolsTitle_msr}')]]
${dsg_ManageSR_ManageServiceRequest_locator}    xpath=//h1[@id="LayoutH1"][text()[contains(.,'${dsg_ManageSR_ManageServiceRequest}')]]
${CustomerServiceRequest_locator}    xpath=//select[@id='category']
${CustomerService_ContactForm_Title_locator}    xpath=//h1[@id="LayoutH1"][text()[contains(.,'${dsg_ContactUs_Category_12_DisplayName}')]]    # xpath=//h1[@id="LayoutH1"][text()[contains(.,'Customer Service')]]
${LicensingAssistance_ContactForm_Title_locator}    xpath=//h1[@id="LayoutH1"][text()[contains(.,'${dsg_ContactUs_Category_11_DisplayName}')]]
${RenewalsAssistance_ContactForm_Title_locator}    xpath=//h1[@id="LayoutH1"][text()[contains(.,'${dsg_ContactUs_Category_2_DisplayName}')]]
${ProfessionalServicesAssistance_ContactForm_Title_locator}    xpath=//h1[@id="LayoutH1"][text()[contains(.,'${dsg_ContactUs_Category_3_DisplayName}')]]
${RequestProductInformation_ContactForm_Title_locator}    xpath=//h1[@id="LayoutH1"][text()[contains(.,'${dsg_ContactUs_Category_4_DisplayName}')]]
${TrainingAssistance_ContactForm_Title_locator}    xpath=//h1[@id="LayoutH1"][text()[contains(.,'${dsg_ContactUs_Category_1_DisplayName}')]]
${at_CustomService_select_product}    xpath=//div[@id="divSelProd"]//select[@id="SelectedProductId"]
${at_ContactFormPlaceholder}    xpath=//div[@id="ContactFormPlaceholder"]
${at_RegistrationAssistance_ContactFormPlaceholder}    xpath=//div[@id="ContactFormPlaceholder"]
${dsg_CreateSR_KBDescription_locator}    xpath=//div[@id='KB_articles'][not(@style='display: none;')]//p[text()[contains(., '${dsg_CreateSR_KBDescription}')]]
${dsg_CustomerServiceForm_RelevantArticles_Submit_locator}    xpath=//div[@id='KB_articles'][not(@style='display: none;')]//a[text()[contains(., '${dsg_CustomerServiceForm_RelevantArticles_Submit}')]]
${dsg_ContactUs_EmailConfirmationMsg_locator}    xpath=//div[@id="PolarisAlertMessage"]//p[text()[contains(., "${dsg_ContactUs_EmailConfirmationMsg}")]]    # xpath=//div[@id="PolarisNotificationMessage"]//p[text()[contains(., "${dsg_ContactUs_EmailConfirmationMsg}")]]
${dsg_LicenseForm_RelevantArticles_Submit_locator}    xpath=//div[@id="KB_articles"]//a[text()[contains(., "${dsg_LicenseForm_RelevantArticles_Submit}")]]
${dsg_ProductSearch_WarmTransferTitle_locator}    xpath=//div[@class="modal-content"]//h3[text()[contains(., '${dsg_ProductSearch_WarmTransferTitle}')]]//ancestor::div[@id="wTransferDialog"]
${dsg_ProductSearch_modalBtnContinue_locator}    ${dsg_ProductSearch_WarmTransferTitle_locator}[@aria-hidden='false']//input[@value[contains(., '${dsg_ProductSearch_modalBtnContinue}')]]
${dsg_ContactUs_Renewals_ProductContact_Instructions_locator}    xpath=//blockquote[//text()[contains(., '${dsg_ContactUs_Renewals_ProductContact_Instructions}')]]
${Customer_Service}    Customer Service
${dsg_CustomerServiceForm_Submit_locator}    xpath=//div[@id='KB_articles'][not(@style='display: none;')]//a[@id='lnkSubmitRequest']
${divNotificationModal_Alert_Title_locator}    xpath=//div[@id='divNotificationModal'][@aria-hidden='false']//div[@class='modal-header']//h3[text()[contains(., '${dsg_CreateSR_Alert_Title}')]]
${okButton_divNotificationModal}    xpath=//div[@id='divNotificationModal'][@aria-hidden='false']//a[@id='ok-button']
${dsg_ContactUs_Topic_locator}    xpath=//div[@id="divTopics"]//select[@id="Topics"]
