*** Variables ***
${RegisterProductOrLicenseModal}    xpath=//div[@id='RegisterProductOrLicenseModal']
${dsg_MyAccount_PageTitle_MyProductSupport_locator}    ${RegisterProductOrLicenseModal}[@aria-hidden='false']//h1[@id="LayoutH1" and text()[contains(., '${dsg_MyAccount_PageTitle_MyProductSupport}')]]
${button_Close_RegisterProductOrLicenseModal}    ${RegisterProductOrLicenseModal}[@aria-hidden='false']//button[@id='btnCloseLic']
${button_Save_RegisterProductOrLicenseModal}    ${RegisterProductOrLicenseModal}[@aria-hidden='false']//button[@id='btnSaveLic']
${ViewSubscribersModal}    xpath=//div[@id='ViewSubscribersModal']
${dsg_Licensing_View_License_Users_Title}    ${ViewSubscribersModal}[@aria-hidden='false']//div[@class='modal-header']//h3[text()[contains(., '${dsg_Licensing_View_License_Users}')]]
${closeButton_ViewSubscribersModall}    ${ViewSubscribersModal}[@aria-hidden='false']//button[text()[contains(., '${General_Close}')]]
${RequestSubscriptionModal}    xpath=//div[@id='RequestSubscriptionModal']
${dsg_Licensing_Request_License_User_Access_Title}    ${RequestSubscriptionModal}[@aria-hidden='false']//div[@class='modal-header']//h3[text()[contains(., '${dsg_Licensing_Request_License_User_Access}')]]
${cancelButton_RequestSubscriptionModal}    ${RequestSubscriptionModal}[@aria-hidden='false']//button[text()[contains(., '${dsg_Licensing_Cancel_Button}')]]
${ManageSubscribersModal}    xpath=//div[@id='ManageSubscribersModal']
${dsg_Licensing_Manage_License_Users_Title}    ${ManageSubscribersModal}[@aria-hidden='false']//div[@class='modal-header']//h3[text()[contains(., '${dsg_Licensing_Manage_License_Users}')]]
${closeButton_ManageSubscribersModall}    ${ManageSubscribersModal}[@aria-hidden='false']//button[text()[contains(., '${General_Close}')]]
${AddExpansionUnitModal}    xpath=//div[@id='AddExpansionUnitModal']
${cancelButton_AddExpansionUnitModal}    ${AddExpansionUnitModal}[@aria-hidden='false']//button[text()[contains(., '${dsg_Registration_AddExpansionUnit_CancelButton}')]]
${addButton_AddExpansionUnitModal}    ${AddExpansionUnitModal}[@aria-hidden='false']//button[text()[contains(., '${dsg_Registration_AddExpansionUnit_AddButton}')]]
${assetInput_AddExpansionUnitModal}    ${AddExpansionUnitModal}[@aria-hidden='false']//input[@id='expansionUnitLicenseOrServiceTag']
${AddExpansionModalErrors}    ${AddExpansionUnitModal}[@aria-hidden='false']//div[@id='AddExpansionModalErrors']
${dsg_Registration_AddExpansionUnit_Title_locator}    ${AddExpansionUnitModal}[@aria-hidden='false']//div[@class='modal-header']//h3[text()[contains(., '${dsg_Registration_AddExpansionUnit_Title}')]]
${dsg_RegisterUnKnownProductLicense_Modal_Title_locator}    ${RegisterProductOrLicenseModal}[@aria-hidden='false']//h3[@id="modalRegProdLicTitle" and text()[contains(., '${dsg_RegisterUnKnownProductLicense_Modal_Title}')]]
${at_MyProfile}    xpath=//section[@id="LeftRail"]/dl[./dt[text()[contains(., "${dsg_RRComponentType_33}")]]]/dd/a[text()[contains(., "My Profile")]]
${records_MyProducts_ProductGrid}    ${at_MyProducts_ProductGrid}/tbody/tr[@data-uniqueid]
${column_MyProducts_ProductGrid}    ${at_MyProducts_ProductGrid}/thead/tr/th[.//text()[contains(., '${dsg_MyAccount_GridColCaption_MyProduct}')]]
${column_SupportStatus_ProductGrid}    ${at_MyProducts_ProductGrid}/thead/tr/th[.//text()[contains(., '${dsg_MyAccount_GridColCaption_SupportStatus}')]]
${column_LicenseStatus_ProductGrid}    ${at_MyProducts_ProductGrid}/thead/tr/th[.//text()[contains(., '${dsg_MyAccount_GridColCaption_License}')]]
${column_NewsAlerts_ProductGrid}    ${at_MyProducts_ProductGrid}/thead/tr/th[.//text()[contains(., '${dsg_MyAccount_GridColCaption_NewsAlerts}')]]
${column_OpenSRs_ProductGrid}    ${at_MyProducts_ProductGrid}/thead/tr/th[.//text()[contains(., '${dsg_MyAccount_GridColCaption_OpenSRs}')]]
${column_Downloads_ProductGrid}    ${at_MyProducts_ProductGrid}/thead/tr/th[.//text()[contains(., '${dsg_MyAccount_GridColCaption_Downloads}')]]
${at_newsAlertsDetailGrid}    ${at_MyProducts_ProductGrid}//table[@id='newsAlertsDetailGrid']
${column_NewsAlerts_newsAlertsDetailGrid}    ${at_newsAlertsDetailGrid}/thead/tr/th[.//text()[contains(., '${dsg_MyAccount_NewsAlertsDetail_GridColTitleCaption}')]]
${column_PublishedDate_newsAlertsDetailGrid}    ${at_newsAlertsDetailGrid}/thead/tr/th[.//text()[contains(., '${dsg_MyAccount_NewsAlertsDetail_GridColPublishedCaption}')]]
${at_SRDetailGrid}    ${at_MyProducts_ProductGrid}//table[@id='SRDetailGrid']
${column_ID_SRDetailGrid}    ${at_SRDetailGrid}/thead/tr/th[.//text()[contains(., '${dsg_MyAccount_SRDetail_GridColIDCaption}')]]
${column_RequestTitle_SRDetailGrid}    ${at_SRDetailGrid}/thead/tr/th[.//text()[contains(., '${dsg_MyAccount_SRDetail_GridColTitleCaption}')]]
${column_Product_SRDetailGrid}    ${at_SRDetailGrid}/thead/tr/th[.//text()[contains(., '${dsg_MyAccount_SRDetail_GridColProductCaption}')]]
${column_Status_SRDetailGrid}    ${at_SRDetailGrid}/thead/tr/th[.//text()[contains(., '${dsg_MyAccount_SRDetail_GridColStatusCaption}')]]
${column_CreatedOn_SRDetailGrid}    ${at_SRDetailGrid}/thead/tr/th[.//text()[contains(., '${dsg_MyAccount_SRDetail_GridColCreatedCaption}')]]
${column_UpdatedOn_SRDetailGrid}    ${at_SRDetailGrid}/thead/tr/th[.//text()[contains(., '${dsg_MyAccount_SRDetail_GridColUpdatedCaption}')]]
${at_DownloadDetailGrid}    ${at_MyProducts_ProductGrid}//table[@id='DownloadDetailGrid']
${column_FileName_DownloadDetailGrid}    ${at_DownloadDetailGrid}/thead/tr/th[.//text()[contains(., '${dsg_MyAccount_DownloadDetail_GridColFileNameCaption}')]]
${column_ReleaseDate_DownloadDetailGrid}    ${at_DownloadDetailGrid}/thead/tr/th[.//text()[contains(., '${dsg_MyAccount_DownloadDetail_GridColReleaseDateCaption}')]]
${column_DownloadedOn_DownloadDetailGrid}    ${at_DownloadDetailGrid}/thead/tr/th[.//text()[contains(., '${dsg_MyAccount_DownloadDetail_GridColDownloadDateCaption}')]]
${at_licenseDetailGrid}    ${at_MyProducts_ProductGrid}//table[@id='licenseDetailGrid']
${column_License#_LicenseDetailGrid}    ${at_licenseDetailGrid}/thead/tr/th[.//text()[contains(., '${dsg_MyAccount_LicenseDetail_GridColLicenseNumCaption}')]]
${column_Renewal_LicenseDetailGrid}    ${at_licenseDetailGrid}/thead/tr/th[.//text()[contains(., '${dsg_MyAccount_LicenseDetail_GridColRenewalDateCaption}')]]
${column_UserGroup_LicenseDetailGrid}    ${at_licenseDetailGrid}/thead/tr/th[.//text()[contains(., '${dsg_MyAccount_LicenseDetail_GridColUserGroupCaption}')]]
${column_MyRole_LicenseDetailGrid}    ${at_licenseDetailGrid}/thead/tr/th[.//text()[contains(., '${dsg_MyAccount_LicenseDetail_GridColMyRoleCaption}')]]
${at_RegisterNewLicenseLink}    xpath=//div[@id='Licensing']//div[@class='inline-content-links']//a[@id='RegisterNewLicenseLink']
${dsg_Licensing_Licensing_FAQs_locator}    xpath=//div[@id='Licensing']//div[@class='inline-content-links']//a[text()[contains(., '${dsg_Licensing_Licensing_FAQs}')]]
${licensePage_selector_SortBy}    xpath=//div[@id='Licensing']//div[@class='inline-content-links']//select[@id='SortBy']
${dsg_Licensing_Show_Registered_Licenses_locator}    xpath=//div[@id='Licensing']//div[@class='inline-content-links']//a[@id='ShowRegisteredLicensesLink']
${at_LicensesFAQ}    xpath=//div[@id='LicFAQ']
${div_Licensing}    xpath=//div[@id='Licensing']
${list_licenses_locator}    ${div_Licensing}//div[@data-lic]
${licensesDetail_tab_detail}    //ul[@class='nav nav-tabs'][./ancestor::div[1][@data-lic]]/li[@class[contains(., 'detail-tab')]]/a/span[@class='tab-text two-tabs product-name']
${licensesDetail_tab_retrieve}    //ul[@class='nav nav-tabs'][./ancestor::div[1][@data-lic]]/li[@class[contains(., 'retrieve-tab')]]/a/span[@class='tab-text two-tabs']
${licensesDetail_tab_warranty}    //ul[@class='nav nav-tabs'][./ancestor::div[1][@data-lic]]/li[@class[contains(., 'warranty-tab')]]/a/span[@class='tab-text two-tabs']
${licensesDetail_tab_component}    //ul[@class='nav nav-tabs'][./ancestor::div[1][@data-lic]]/li[@class[contains(., 'component-tab')]]/a/span[@class='tab-text two-tabs']
${licensesDetail_tabPanel_retrieve}    ${list_licenses_locator}//div[@class='tab-content']//div[@id[contains(., 'retrieve-panel-')]]
${dsg_Licensing_Retrieve_Key_Add_Expansion_Unit_locator}    //button[text()[normalize-space()][contains(., '${dsg_Licensing_Retrieve_Key_Add_Expansion_Unit}')]]
${Licensing_Retrieve_Key_ExpansionUnit_rows}    ${dsg_Licensing_Retrieve_Key_Add_Expansion_Unit_locator}/following-sibling::table/tbody/tr
${Licensing_Retrieve_Key_TransferKey_rows}    //div[@id[contains(., 'lic-')]][.${dsg_Licensing_Retrieve_Key_Transfer_Key_locator}]//table/tbody/tr
${dsg_Licensing_Retrieve_Key_Transfer_Key_locator}    //button[text()[normalize-space()][contains(., '${dsg_Licensing_Transfer_Key}')]]
${licensePage_nameField_LicenseNumber}    ${list_licenses_locator}//div[@class='tab-content']//div[@id[contains(., 'detail-panel-')]]//dl[@class='dl-horizontal'][1][not(following::sibling)]/dt[text()[normalize-space()][starts-with(., '${Label_LicenseNumber}')]][1][not(following::sibling)]
${licensePage_nameField_RelatedLicenseNumber}    ${list_licenses_locator}//div[@class='tab-content']//div[@id[contains(., 'detail-panel-')]]//dl[@class='dl-horizontal'][1][not(following::sibling)]/dt[text()[normalize-space()][starts-with(., '${dsg_Licensing_RelatedLicenseNumber}')]][1][not(following::sibling)]
${licensePage_nameField_PrimaryServiceTag}    ${list_licenses_locator}//div[@class='tab-content']//div[@id[contains(., 'detail-panel-')]]//dl[@class='dl-horizontal'][1][not(following::sibling)]/dt[text()[normalize-space()][starts-with(., '${dsg_Licensing_PrimaryServiceTag}')]][1][not(following::sibling)]
${licensePage_nameField_Description}    ${list_licenses_locator}//div[@class='tab-content']//div[@id[contains(., 'detail-panel-')]]//dl[@class='dl-horizontal'][1][not(following::sibling)]/dt[text()[normalize-space()][starts-with(., '${dsg_General_Description}')]][1][not(following::sibling)]
${licensePage_nameField_Version}    ${list_licenses_locator}//div[@class='tab-content']//div[@id[contains(., 'detail-panel-')]]//dl[@class='dl-horizontal'][1][not(following::sibling)]/dt[text()[normalize-space()][starts-with(., '${dsg_General_Version}')]][1][not(following::sibling)]
${licensePage_nameField_Group}    ${list_licenses_locator}//div[@class='tab-content']//div[@id[contains(., 'detail-panel-')]]//dl[@class='dl-horizontal'][1][not(following::sibling)]/dt[text()[normalize-space()][starts-with(., '${dsg_Licensing_Group}')]][1][not(following::sibling)]
${licensePage_nameField_LicenseUser}    ${list_licenses_locator}//div[@class='tab-content']//div[@id[contains(., 'detail-panel-')]]//dl[@class='dl-horizontal'][1][not(following::sibling)]/dt[text()[normalize-space()][contains(., '${dsg_Licensing_License_User}')]][1][not(following::sibling)]
${licensePage_nameField_QuantityOwned}    ${list_licenses_locator}//div[@class='tab-content']//div[@id[contains(., 'detail-panel-')]]//dl[@class='dl-horizontal'][1][not(following::sibling)]/dt[text()[normalize-space()][starts-with(., '${dsg_Licensing_Quantity_Owned}')]][1][not(following::sibling)]
${licensePage_nameField_UnderMaintenance}    ${list_licenses_locator}//div[@class='tab-content']//div[@id[contains(., 'detail-panel-')]]//dl[@class='dl-horizontal'][1][not(following::sibling)]/dt[text()[normalize-space()][starts-with(., '${dsg_Licensing_Under_Maintenance}')]][1][not(following::sibling)]
${licensePage_nameField_LicenseRenewal}    ${list_licenses_locator}//div[@class='tab-content']//div[@id[contains(., 'detail-panel-')]]//dl[@class='dl-horizontal'][1][not(following::sibling)]/dt[text()[normalize-space()][starts-with(., '${dsg_Licensing_License_Renewal}')]][1][not(following::sibling)]
${licensePage_nameField_WarrantyExpiration}    ${list_licenses_locator}//div[@class='tab-content']//div[@id[contains(., 'detail-panel-')]]//dl[@class='dl-horizontal'][1][not(following::sibling)]/dt[text()[normalize-space()][starts-with(., '${dsg_Licensing_WarrantyExpiration}')]][1][not(following::sibling)]
${licensePage_nameLink_ManageGroupAssignment}    ${licensePage_nameField_Group}/following::*[1]/self::dd//a[text()[contains(., '${dsg_Licensing_Manage_Group_Assignment}')]]
${licensePage_nameLink_SeeAll}    ${licensePage_nameField_LicenseUser}/following::*[1]/self::dd//a[text()[contains(., '${dsg_Licensing_See_All}')]]
${licensePage_nameLink_RequestLicenseAccess}    ${licensePage_nameField_LicenseUser}/following::*[1]/self::dd//a[text()[contains(., '${dsg_Licensing_Request_License_Access}')]]
${licensePage_nameLink_ManageLicenseUsers}    ${licensePage_nameField_LicenseUser}/following::*[1]/self::dd//a[text()[contains(., '${dsg_Licensing_Manage_License_Users}')]]
${licenses_UserIsLicense}    //div[@class='tab-content']//div[@id[contains(., 'detail-panel-')]]//dl[@class='dl-horizontal'][1][not(following::sibling)]/dt[text()[normalize-space()][contains(., '${dsg_Licensing_License_User}')]][1][not(following::sibling)]/following::*[1]/self::dd//a[text()[contains(., '${dsg_Licensing_See_All}') or contains(., '${dsg_Licensing_Manage_License_Users}')]]
${licenses_UserIsNotLicense}    //div[@class='tab-content']//div[@id[contains(., 'detail-panel-')]]//dl[@class='dl-horizontal'][1][not(following::sibling)]/dt[text()[normalize-space()][contains(., '${dsg_Licensing_License_User}')]][1][not(following::sibling)]/following::*[1]/self::dd//a[text()[contains(., '${dsg_Licensing_Request_License_Access}')]]
${dsg_MyAccount_MyGroup_Title_locator}    xpath=//h1[@id="LayoutH1"][text()[contains(., '${dsg_MyAccount_MyGroup_Title}')]]
${licensePage_FilterProduct_header}    xpath=//div[@id='FilterPanel']//div[@id='PLCProduct']/preceding-sibling::div[@class='panel-heading']/h4[@class='panel-title']/a
${licensePage_FilterLicenseNumber_header}    xpath=//div[@id='FilterPanel']//div[@id='PLCLicenseNumber']/preceding-sibling::div[@class='panel-heading']/h4[@class='panel-title']/a
${licensePage_FilterServiceTag_header}    xpath=//div[@id='FilterPanel']//div[@id='PLCServiceTag']/preceding-sibling::div[@class='panel-heading']/h4[@class='panel-title']/a
${licensePage_FilterLicenseUser_header}    xpath=//div[@id='FilterPanel']//div[@id='PLCLicenseUser']/preceding-sibling::div[@class='panel-heading']/h4[@class='panel-title']/a
${licensePage_FilterGroups_header}    xpath=//div[@id='FilterPanel']//div[@id='PLCLicenseGroup']/preceding-sibling::div[@class='panel-heading']/h4[@class='panel-title']/a
${licensePage_FilterRenewalDate_header}    xpath=//div[@id='FilterPanel']//div[@id='PLCRenewalDate']/preceding-sibling::div[@class='panel-heading']/h4[@class='panel-title']/a
${column_LicenseNumber_ExpansionUnitGrid}    ${dsg_Licensing_Retrieve_Key_Add_Expansion_Unit_locator}/following-sibling::table/thead/tr/th[.//text()[contains(., '${dsg_Licensing_Retrieve_Key_License_Number}')]]
${column_Product_ExpansionUnitGrid}    ${dsg_Licensing_Retrieve_Key_Add_Expansion_Unit_locator}/following-sibling::table/thead/tr/th[.//text()[contains(., '${dsg_Licensing_Retrieve_Product}')]]
${column_ExpansionUnitServiceTag_ExpansionUnitGrid}    ${dsg_Licensing_Retrieve_Key_Add_Expansion_Unit_locator}/following-sibling::table/thead/tr/th[.//text()[contains(., '${dsg_Licensing_Retrieve_Key_Expansion_Unit_Service_Tag}')]]
${column_PropertyName_TransferKeyGrid}    //div[@id[contains(., 'lic-')]][.${dsg_Licensing_Retrieve_Key_Transfer_Key_locator}]//table/thead/tr/td[.//text()[contains(., 'Property Name')]]
${column_PropertyValue_TransferKeyGrid}    //div[@id[contains(., 'lic-')]][.${dsg_Licensing_Retrieve_Key_Transfer_Key_locator}]//table/thead/tr/td[.//text()[contains(., 'Property Value')]]
${div_Groups}     xpath=//div[@class='user-groups']
${div_groupList}    ${div_Groups}//div[@id='groupList']
${list_groups_locator}    ${div_groupList}//div[@data-group-name]
${groupsPage_tab_TabGroupData}    //ul[@id='MyGroupTabContainer'][./ancestor::div[@data-group-name]]//a[@name='TabGroupData']
${groupsPage_tab_TabGroupMembers}    //ul[@id='MyGroupTabContainer'][./ancestor::div[@data-group-name]]//a[@name='TabGroupMembers']
${groupsPage_tabPanel_members}    //div[@class='tab-content']//div[@id[contains(., '_members')]]
${groupsPage_nameField_GroupName}    ${list_groups_locator}//div[@class='tab-content']//div[@name='GroupInfoContainer']//dl[@class='dl-horizontal' and @id='GroupDataContainer'][1][not(following::sibling)]/dt[text()[normalize-space()][starts-with(., 'Group Name')]][1][not(following::sibling)]
${groupsPage_nameField_Description}    ${list_groups_locator}//div[@class='tab-content']//div[@name='GroupInfoContainer']//dl[@class='dl-horizontal' and @id='GroupDataContainer'][1][not(following::sibling)]/dt[text()[normalize-space()][starts-with(., 'Description')]][1][not(following::sibling)]
${groupsPage_nameField_Products}    ${list_groups_locator}//div[@class='tab-content']//div[@name='GroupInfoContainer']//dl[@class='dl-horizontal' and @id='GroupDataContainer'][1][not(following::sibling)]/dt[text()[normalize-space()][starts-with(., 'Products')]][1][not(following::sibling)]
${groupsPage_nameField_MembershipVisibility}    ${list_groups_locator}//div[@class='tab-content']//div[@name='GroupInfoContainer']//dl[@class='dl-horizontal' and @id='GroupDataContainer'][1][not(following::sibling)]/dt[text()[normalize-space()][starts-with(., 'Membership Visibility')]][1][not(following::sibling)]
${groupPage_FilterGroups_header}    xpath=//div[@id='accordion']//div[@id='FilterGroupPanel']/preceding-sibling::div[@class='panel-heading']/h4[@class='panel-title']/a
${groupPage_FilterProduct_header}    xpath=//div[@id='accordion']//div[@id='FilterProductPanel']/preceding-sibling::div[@class='panel-heading']/h4[@class='panel-title']/a
${groupPage_FilterMembers_header}    xpath=//div[@id='accordion']//div[@id='FilterLicensePanel']/preceding-sibling::div[@class='panel-heading']/h4[@class='panel-title']/a
${groupPage_FilterMyRole_header}    xpath=//div[@id='accordion']//div[@id='FilterRolePanel']//ancestor::div[@class='panel panel-default'][1]
${groupPage_Btn_EditGroup}    //i[@name='Btn_EditGroup']
${groupPage_ChkMembershipVisibility}    //input[@id='ChkMembershipVisibility']
${groupPage_Btn_SaveGroupInfo}    //div[@id='ContainerBackEditGroup']//button[@name='Btn_SaveGroupInfo']
${icon_ProcessingGroupSearch}    xpath=//i[@id='ProcessingGroupSearch']
${groupPage_selector_SortBy}    ${div_Groups}//div[@class='inline-content-links']//select[@id='ddlSortBy']
${groupPage_Link_AddGroup}    ${div_Groups}//div[@class='inline-content-links']//a[@id='BtnAddGroup']
${groupPage_Link_GroupsFAQ}    ${div_Groups}//div[@class='inline-content-links']//a[text()[contains(., '${dsg_MyAccount_MyGroup_Help}')]]
${at_GroupFAQ}    xpath=//div[@id='GroupFAQ']
${groupPage_column_Name_MembersGrid}    ${groupsPage_tabPanel_members}//tbody/tr[1]/th[.//text()[contains(., 'Name')]]
${groupPage_column_EmailId_MembersGrid}    ${groupsPage_tabPanel_members}//tbody/tr[1]/th[.//text()[contains(., 'Email Id')]]
${groupPage_column_Admin_MembersGrid}    ${groupsPage_tabPanel_members}//tbody/tr[1]/th[.//text()[contains(., 'Admin')]]
${groupPage_column_Support_MembersGrid}    ${groupsPage_tabPanel_members}//tbody/tr[1]/th[.//text()[contains(., 'Support')]]
${groupPage_column_LicenseUser_MembersGrid}    ${groupsPage_tabPanel_members}//tbody/tr[1]/th[.//text()[contains(., 'License User')]]
${modalRegisterProduct_Field_LicenseNumber}    ${RegisterProductOrLicenseModal}[@aria-hidden='false']//input[@id='licenseNumber']
${modalRegisterProduct_Field_Group}    ${RegisterProductOrLicenseModal}[@aria-hidden='false']//input[@id='group']
${modalRegisterProduct_Button_Search}    ${RegisterProductOrLicenseModal}[@aria-hidden='false']//button[@id='MyAccountLicenseModalSearch']/i
${modalRegisterProduct_icon_processingLicReg}    ${RegisterProductOrLicenseModal}[@aria-hidden='false']//i[@id='processingLicReg']
${modalRegisterProduct_error_RegProdLicError}    ${RegisterProductOrLicenseModal}[@aria-hidden='false']//div[@id='RegProdLicError']
${modalRegisterProduct_Button_SaveChanges}    ${RegisterProductOrLicenseModal}[@aria-hidden='false']//div[@id='btnSaveLic']
${modalRegisterProduct_error_link_ViewLicense}    ${RegisterProductOrLicenseModal}[@aria-hidden='false']//div[@id='RegProdLicError']//a
${dsg_Licensing_ViewLicense_Page_Title_locator}    xpath=//h1[@id="LayoutH1"][text()[contains(., '${dsg_Licensing_ViewLicense_Page_Title}')]]
${paginationInfo}    xpath=//span[@class='pagination-info']
${paginationInfo_buttonNext}    ${paginationInfo}//a[@id='mainGridnextButton' and @data-action='next']
${paginationInfo_totalPages}    ${paginationInfo}//span[@id='mainGridtotalPages']
${profilePage_DellSoftwareProfile_panel}    xpath=//div[@id='DellSoftwareProfile' and @role='tabpanel']
${profilePage_MyGroupMembership_panel}    xpath=//div[@id='MyGroupMembership' and @role='tabpanel']
${profilePage_MyLoginCredentials_panel}    xpath=//div[@id='MyLoginCredentials' and @role='tabpanel']
${profilePage_MySubscriptions_panel}    xpath=//div[@id='MySubscriptions' and @role='tabpanel']
${profilePage_profileEdit}    ${profilePage_DellSoftwareProfile_panel}//a[@id='profileEditId']/i
${profilePage_SaveProfile_button}    ${profilePage_DellSoftwareProfile_panel}//button[@id='SaveProfile']
${profilePage_profileButtonsId}    ${profilePage_DellSoftwareProfile_panel}//div[@id='profileButtonsId' and @style='display: none;']
${profilePage_GroupMembershipGrid}    ${profilePage_MyGroupMembership_panel}//table[@id='GroupMembershipTable']
${profilePage_column_GroupName_GroupMembershipGrid}    ${profilePage_GroupMembershipGrid}//thead/tr/th[.//text()[contains(., '${dsg_ManageProfile_GroupMembership_Tab_GroupName}')]]
${profilePage_column_Role_GroupMembershipGrid}    ${profilePage_GroupMembershipGrid}//thead/tr/th[.//text()[contains(., '${dsg_ManageProfile_GroupMembership_Tab_Role}')]]
${profilePage_column_Share_GroupMembershipGrid}    ${profilePage_GroupMembershipGrid}//thead/tr/th[.//text()[contains(., '${dsg_ManageProfile_GroupMembership_Tab_ShareEmailWithGroup}')]]
${profilePage_EmailChangeRequestId_link}    ${profilePage_DellSoftwareProfile_panel}//a[@id='EmailChangeRequestId']
${profilePage_ChangeDSGPassword_link}    ${profilePage_DellSoftwareProfile_panel}//a[text()[contains(., '${dsg_ChangeDSGPassword}')]]
${profilePage_DellSoftwareProfile_tab}    xpath=//ul[@class='nav nav-tabs']/li/a[@role='tab'][text()[contains(., '${dsg_ManageProfile_Tab1_DellSoftwareProfile}')]]
${profilePage_MyLoginCredentials_tab}    xpath=//ul[@class='nav nav-tabs']/li/a[@role='tab'][text()[contains(., '${dsg_ManageProfile_Tab3_MyLoginCredentials}')]]
${profilePage_MyGroupMembership_tab}    xpath=//ul[@class='nav nav-tabs']/li/a[@role='tab'][text()[contains(., '${dsg_ManageProfile_Tab2_MyGroupMembership}')]]
${profilePage_MySubscriptions_tab}    xpath=//ul[@class='nav nav-tabs']/li/a[@role='tab'][text()[contains(., '${dsg_ManageProfile_Tab4_MySubscriptions}')]]
${profilePage_MyGroupMembership_tab}    xpath=//ul[@class='nav nav-tabs']/li/a[@role='tab'][text()[contains(., '${dsg_ManageProfile_Tab2_MyGroupMembership}')]]
${profilePage_dsgacct_locator}    ${profilePage_MyLoginCredentials_panel}//div[@id='dsgacct']
