*** Variables ***
${at_SignIn_emailAddress}    ${at_body_SignIn}//input[@id="username"]
${at_SignIn_password}    ${at_body_SignIn}//input[@id="password"]
${at_SigIn_buttonSignIn}    ${at_body_SignIn}//button[@id="kc-login"]
${at_SignIn_rememberMe}    ${at_body_SignIn}//input[@id='rememberMe']
${at_CreatePass_tempPass}    xpath=//input[@id='TempPassword']
${at_CreatePass_newPass}    xpath=//input[@id='NewPassword']
${at_CreatePass_confirmPass}    xpath=//input[@id='NewPassword2']
${at_CreatePass_buttonCreatePass}    xpath=//button[@id="createPass"]    # xpath=//button[@id='kc-update-password']
${at_SignOutLink}    xpath=//div[@id='Profile']//a[@id='SignOutLink']
${at_dsg_General_SignOut}    xpath=//div[@id='Profile']//a[text()[contains(.,'${dsg_General_SignOut}')]]
${at_dsg_MyProfile_Label}    xpath=//div[@id='SignInFlyout']//a[text()='${dsg_MyProfile_Label}']
${dsg_ManageProfile_Title_locator}    xpath=//h1[@id="LayoutH1"][text()[contains(., '${dsg_ManageProfile_Title}')]]
${dsg_MyAccount_PageTitle_MyProductSupport_locator}    xpath=//h1[@id="LayoutH1"][text()[contains(., '${dsg_MyAccount_PageTitle_MyProductSupport}')]]
${dsg_ManageProfile_Tab1_DellSoftwareProfile_locator}    xpath=//div[@id="Canvas"]//ul[@class="nav nav-tabs"]/li/a[@href="#DellSoftwareProfile"]
${dsg_ManageProfile_Label_EmailAddress_locator}    xpath=//div[@id="divContactInformation"]//div[./label[text()="${dsg_ManageProfile_Label_EmailAddress}"]]
${at_ManageProfile_FirstName}    //div[@id="divContactInformation"]//input[@id="FirstName"]
${at_ManageProfile_LastName}    //div[@id="divContactInformation"]//input[@id="LastName"]
${at_ManageProfile_PhoneNumber}    //div[@id="divContactInformation"]//input[@id="PhoneNumber"]
${at_MyProducts}    xpath=//section[@id="LeftRail"]/dl[./dt[text()[contains(., "${dsg_RRComponentType_33}")]]]/dd/a[text()[contains(., "My Products")]]
${at_SignInButton}    xpath=//div[@id='Profile']//i[@class='i-small-useraccount' or @class='i-small-useraccount flyout-open']
${at_MyProducts_ProductGrid}    xpath=//div[@id='MainContent']//table[@id='ProductGrid']
${at_MyLicenses}    xpath=//section[@id="LeftRail"]/dl[./dt[text()[contains(., "${dsg_RRComponentType_33}")]]]/dd/a[text()[contains(., "My Licenses")]]
${dsg_Licensing_Landing_Page_Title_locator}    xpath=//h1[@id="LayoutH1"][text()[contains(., '${dsg_Licensing_Landing_Page_Title}')]]
${at_CreatNewPassword_Title_locator}    ${at_body_ChangePassword-NewRegistration}//h1
${at_CreatePass_UserName}    xpath=//input[@id='UserName']
${at_dsg_MyAccount_Label}    xpath=//div[@id='SignInFlyout']//a[text()[contains(.,'${dsg_MyAccount_Label}')]]
${url_To_License}    /my-account/licensing
${dsg_MyAccount_GridColCaption_MyProduct_locator}    xpath=//div[@id="MainContent"]//table[@id="ProductGrid"]/thead//th/div[text()[contains(., "${dsg_MyAccount_GridColCaption_MyProduct}")]]
${at_link_ForgotPassword}    ${at_body_SignIn}//div[@id="reset-password"]//a    # xpath=//form//div/a[@href[contains(., '/account/ForgotPassword/')]]
${at_ResetPassword_Title_locator}    ${at_body_ResetPassword}
${at_body_ResetPassword}    xpath=//form[@id='kc-reset-password-form']
${at_buttom_ResetPassword}    ${at_body_ResetPassword}//button[@type="submit"]
${at_body_UpdatePassword}    xpath=//form[@id='kc-passwd-update-form']
${at_UpdatePassword_oldPass}    ${at_body_UpdatePassword}//input[@id='old-password']
${at_UpdatePassword_username}    ${at_body_UpdatePassword}//input[@id='username']
${at_UpdatePassword_newPass}    ${at_body_UpdatePassword}//input[@id='new-password']
${at_buttom_UpdatePassword}    ${at_body_UpdatePassword}//button[@id='kc-update-password']
${at_body_SignIn}    xpath=//form[@id="kc-form-login"]    # //body[@data-pagelocation="SignIn"]
${at_body_ChangePassword-ResetPassword}    xpath=//form[@id='kc-passwd-update-form']
${at_ResetPassword_password}    ${at_body_ChangePassword-ResetPassword}//input[@id='password']
${at_ResetPassword_button}    ${at_body_ChangePassword-ResetPassword}//button[@id='kc-update-password']
${at_body_ChangePassword-NewRegistration}    xpath=//body[@data-pagelocation='ChangePassword-NewRegistration' or @data-pagelocation='ChangePassword-ResetPassword']
${at_body_EditPassword}    xpath=//body[@data-pagelocation='ChangePassword-ChangePassword']
${at_EditPassword_Title_locator}    ${at_body_EditPassword}//h1
${at_UpdatePassword_Title_locator}    xpath=//div[@id='kc-header'][following-sibling::div[@id='kc-content'][.//div[@id='dib-update-password']]]
${at_alert_SignIn}    //div[@class='edc-alerts__col']
${at_alert_text_SignIn}    //div[@class='edc-alerts__col']//span[@ng-bind-html='alert.msg']/text()
${at_PasswordChanged_Title_locator}    xpath=//div[@id='kc-header'][following-sibling::div[@id='kc-content'][.//div[@id='kc-info-message']]]    # xpath=//div[@id='kc-header'][following-sibling::div[@id='kc-content'][.//div[@id='kc-info-message'][.//text()[contains(., 'You have successfully changed the password')]]]]
${at_BackToApp_locator}    xpath=//div[@id='kc-content']//a[@id='kc-login']
